# Generated by Django 2.2.4 on 2022-04-27 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lineApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='line',
            options={'ordering': ('-publishDate',), 'verbose_name': '经典语录', 'verbose_name_plural': '经典语录'},
        ),
        migrations.AlterModelOptions(
            name='lineimg',
            options={'verbose_name': '图片', 'verbose_name_plural': '图片'},
        ),
        migrations.RemoveField(
            model_name='line',
            name='price',
        ),
        migrations.RemoveField(
            model_name='line',
            name='productType',
        ),
        migrations.AddField(
            model_name='line',
            name='lineType',
            field=models.CharField(choices=[('动漫语录', '动漫语录'), ('书籍名句', '书籍名句'), ('小说摘抄', '小说摘抄')], default=1, max_length=50, verbose_name='分类大全'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='line',
            name='title',
            field=models.CharField(max_length=50, verbose_name='出自'),
        ),
        migrations.AlterField(
            model_name='lineimg',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineImgs', to='lineApp.line', verbose_name='经典语录'),
        ),
        migrations.AlterField(
            model_name='lineimg',
            name='photo',
            field=models.ImageField(blank=True, upload_to='line/', verbose_name='图片'),
        ),
    ]
