# Generated by Django 2.2.4 on 2022-05-06 11:15

import DjangoUeditor.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='anecodote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='新闻中心')),
                ('description', DjangoUeditor.models.UEditorField(default='', verbose_name='内容')),
                ('anecodoteType', models.CharField(choices=[('附近新闻', '附近新闻'), ('网络趣事', '网络趣事')], max_length=50, verbose_name='分类大全')),
                ('publishDate', models.DateTimeField(default=django.utils.timezone.now, max_length=20, verbose_name='发布时间')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
            ],
            options={
                'verbose_name': '逸闻',
                'verbose_name_plural': '逸闻',
                'ordering': ['-publishDate'],
            },
        ),
    ]
