# Generated by Django 2.2.4 on 2022-05-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anecodoteApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anecodote',
            name='anecodoteType',
            field=models.CharField(choices=[('附近趣事', '附近趣事'), ('网络趣闻', '网络趣闻')], max_length=50, verbose_name='分类大全'),
        ),
    ]
