# Generated by Django 2.2.4 on 2022-06-11 11:30

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tit', models.CharField(max_length=200, verbose_name='标题')),
                ('img', models.FileField(upload_to='media/img', verbose_name='图片')),
                ('conten', DjangoUeditor.models.UEditorField(verbose_name='内容')),
                ('c_tim', models.DateField(verbose_name='创建日期')),
            ],
        ),
        migrations.CreateModel(
            name='coments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('com', models.TextField(blank=True, null=True, verbose_name='留言')),
                ('tim', models.DateField(auto_now_add=True)),
                ('To', models.ForeignKey(on_delete=None, related_name='comen', to='shareApp.article')),
            ],
        ),
    ]
