# Generated by Django 2.2.4 on 2022-06-11 17:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shareApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-c_tim',), 'verbose_name': '文章内容', 'verbose_name_plural': '文章内容'},
        ),
        migrations.AlterField(
            model_name='article',
            name='c_tim',
            field=models.DateTimeField(default=django.utils.timezone.now, max_length=20, verbose_name='发布时间'),
        ),
    ]
