# Generated by Django 2.2.4 on 2022-06-12 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shareApp', '0002_auto_20220612_0107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coments',
            options={'verbose_name': '文章评论', 'verbose_name_plural': '文章评论'},
        ),
    ]
