# Generated by Django 2.2.4 on 2022-06-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareApp', '0003_auto_20220612_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='coments',
            name='parent',
            field=models.ForeignKey(blank=True, default=1, on_delete=None, related_name='replies', to='shareApp.coments', verbose_name='回复'),
            preserve_default=False,
        ),
    ]
