# Generated by Django 2.2.4 on 2022-06-14 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shareApp', '0004_coments_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coments',
            name='parent',
        ),
    ]
