# Generated by Django 2.2.4 on 2022-06-11 11:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='出自')),
                ('description', models.TextField(verbose_name='详情描述')),
                ('lineType', models.CharField(choices=[('python', 'python'), ('linux', 'linux')], max_length=50, verbose_name='分类大全')),
                ('description2', models.TextField(verbose_name='经典语录')),
                ('description3', models.TextField(verbose_name='个人评价')),
                ('publishDate', models.DateTimeField(default=django.utils.timezone.now, max_length=20, verbose_name='发布时间')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
            ],
            options={
                'verbose_name': '经典语录',
                'verbose_name_plural': '经典语录',
                'ordering': ('-publishDate',),
            },
        ),
        migrations.CreateModel(
            name='studyImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='study/', verbose_name='图片')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studyImgs', to='studyApp.study', verbose_name='经典语录')),
            ],
            options={
                'verbose_name': '图片',
                'verbose_name_plural': '图片',
            },
        ),
    ]
