# Generated by Django 2.2.4 on 2022-06-12 03:07

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='study',
            old_name='lineType',
            new_name='studyType',
        ),
        migrations.RemoveField(
            model_name='study',
            name='description3',
        ),
        migrations.AlterField(
            model_name='study',
            name='description',
            field=models.TextField(verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='study',
            name='description2',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='study',
            name='title',
            field=models.CharField(max_length=50, verbose_name='标题'),
        ),
        migrations.DeleteModel(
            name='studyImg',
        ),
    ]
