# Generated by Django 2.2.4 on 2022-06-12 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyApp', '0002_auto_20220612_1107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='study',
            options={'ordering': ('-publishDate',), 'verbose_name': '学习中心', 'verbose_name_plural': '学习中心'},
        ),
    ]
