# Generated by Django 2.2.4 on 2022-04-20 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartoon',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
