# Generated by Django 2.2.4 on 2022-05-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbyApp', '0002_cartoon_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartoon',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='动漫简介'),
        ),
        migrations.AlterField(
            model_name='cartoon',
            name='photo',
            field=models.ImageField(blank=True, upload_to='Cartoon', verbose_name='图片'),
        ),
    ]
