# Generated by Django 2.2.4 on 2022-06-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbyApp', '0003_auto_20220506_1915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartoon',
            options={'verbose_name': '动漫', 'verbose_name_plural': '动漫'},
        ),
        migrations.AlterField(
            model_name='cartoon',
            name='photo',
            field=models.ImageField(blank=True, upload_to='cartoon', verbose_name='图片'),
        ),
    ]
